server:
  port: 8080

xhs:
  redirect-uri: https://zhangle.geekonup.com
  auth-url: https://ad-market.xiaohongshu.com/auth
  token-url: https://adapi.xiaohongshu.com/api/open/oauth2/access_token
  refresh-url: https://adapi.xiaohongshu.com/api/open/oauth2/refresh_token
  accounts:
    - app-id: 8064
      secret: uAlW1LHCMvgjwik4
      name: 极客上线
      advertiser-ids:
        - 8678526
    - app-id: 8070
      secret: IINiMZRz5ddknw7O
      name: GeekOnUp
      advertiser-ids:
        - 6905853
        - 8681016
    - app-id: 8093
      secret: OqRXV5LIu8rEWv8s
      name: 源序科技
      advertiser-ids:
        - 9574874

feishu:
  bitable:
    app-id: cli_a93d04a094b85bdf
    app-secret: u23moIG9VM4SoX5lek5xid8Azxy5Rik0
    app-token: GvH0wd8DmiaeEOkDfTec5g1enJh
    table-id: tblbzaVvwMNJhILB
    account-table-id: tblsqL1mCYsM7r5O